### ISSUE TITLE
Startseite 

### ISSUE THREAD

**Issue by Galaxywarheroes** [Basti-sama/Bengine#13]
Hallo,

ich würde gerne das Universum umbenennen, also dort wo auf dem Bild "Uni 1" steht das möchte ich ändern wo finde ich es im code?

![bengine_3](https://cloud.githubusercontent.com/assets/16124490/11600804/6bdf8c90-9acf-11e5-95b3-47a234057f65.jpg)

Lg

Galaxywarheroes

**Comment by sateffen** [comment]
Das kannst du in der Konfiguration einstellen: https://github.com/Basti-sama/Bengine/blob/cf92821611b5cc7329bcc59cbfbabbee542a622e/app/bootstrap/comm/meta.json

Unter config -> universes -> uni1 -> name einfach deinen Wunschnamen eintragen.

**Comment by Basti-sama** [comment]
Kann man übrigens auch in der Dokumentation nachlesen: http://bengine.de/dokumentation/multi-universum/

**Comment by Galaxywarheroes** [comment]
![bengine_2](https://cloud.githubusercontent.com/assets/16124490/11602859/f324afa6-9add-11e5-9558-930c38149338.jpg)

Habe das ganze geändert das Stimmt doch so oder täusche ich mich hier habe ich alles richtig gemacht?

Habe aber keine Lösung wird mir immer noch angezeigt (Uni 1) habe beide Antworten von euch mal durch geschaut und komme auf keine Lösung habe auch schon meinen Cache gelöscht immer noch nichts..

Mfg

**Comment by sateffen** [comment]
Welchen Cache hast du geleert? Auch den Bengine Cache? Also `/var/cache`? Oder nur den Browsercache?

**Comment by Galaxywarheroes** [comment]
Ja, ich hatte beide geleert, und seit kurzem jetzt Funktioniert das ganze auch!

Danke für eure Hilfe!
